GitHub authentication
afaguilarr/workshop-api-testing-js2 pull request #16
Opened 2018-06-05 01:18 UTC by afaguilarr

2018-06-05 01:22 UTC, afaguilarr commented
No entiendo por qué al enviar la token por medio del travis CI dicha token deja de funcionar, es decir, al ejecutar el código en local corren los tests, pero al intentar hacer el pull request dejan de funcionar en travis CI y en local D:

2018-06-12 13:25 UTC, sorregom requested changes
please check comments

2018-06-12 13:25 UTC, sorregom commented on .eslintrc.yml
> +    "comma-dangle": ["error", "never"]
please add EOF

2018-06-12 13:25 UTC, sorregom commented on .gitignore
> +# End of https://www.gitignore.io/api/node,windows,webstorm
EOF

2018-06-12 13:25 UTC, sorregom commented on .idea/misc.xml
> +<?xml version="1.0" encoding="UTF-8"?>
add 
`.idea/`  to the .gitignote file to keep this file out of the repo, do a rebase to squash the commit with the previous so we can't have track of this file, if you need help we can chat

2018-06-12 13:25 UTC, sorregom commented on .idea/modules.xml
> +<?xml version="1.0" encoding="UTF-8"?>
same, file to delete, do not keep track

2018-06-12 13:25 UTC, sorregom commented on .idea/vcs.xml
> +<?xml version="1.0" encoding="UTF-8"?>
same, file to delete, do not keep track

2018-06-12 13:25 UTC, sorregom commented on .idea/workshop-api-testing-js.iml
> +<?xml version="1.0" encoding="UTF-8"?>
same, file to delete, do not keep track

2018-06-12 13:25 UTC, sorregom commented on .travis.yml
> + - /^v\d+\.\d+\.\d+$/
EOF

2018-06-12 13:25 UTC, sorregom commented on .travis.yml
> +- '6'
you can delete node 6

2018-06-12 13:25 UTC, sorregom commented on test/GithubApi.Authentication.test.js
> +/* // 'd0d5765f05f1a535e0f12d55c6a4e44a11833189'
delete this comments, you should never copy tokens directly to an account

2018-06-12 13:27 UTC, sorregom commented
para que funcione correctamente en travis, al generar el key con travis encrypt... este valor debe quedar dentro del archivo .travis en algo llamado secure, si eso no lo tiene, entonces travis fallará con la autenticación porque buscara una variable en el proceso que no existe

2018-06-13 13:28 UTC, closed without merging